# Generated by Django 3.1.7 on 2021-02-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210221_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdetail',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='review.review'),
            preserve_default=False,
        ),
    ]
