# Generated by Django 3.1.7 on 2021-02-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
